services:
  cadence:
    container_name: cadence
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CADENCE_DB_HOST: cadence-db
      CADENCE_DB_PORT: 5432
      CADENCE_DB_NAME: cadence
      CADENCE_DB_USER: cadence
      CADENCE_DB_PASSWORD: RTYL9d
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      cadence-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/resilience/ready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cadence-db:
    image: postgres:16-alpine
    container_name: cadence-db
    environment:
      POSTGRES_USER: cadence
      POSTGRES_PASSWORD: RTYL9d
      POSTGRES_DB: cadence
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "cadence-db-data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cadence -d cadence" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  cadence-db-data:
