[tools]
go = "1.26"
golangci-lint = "2.12.2"
"go:github.com/ogen-go/ogen/cmd/ogen" = "1.24.0"

[env]
GOOS = "linux"
GOARCH = "amd64"
CGO_ENABLED = "0"

[tasks.default]
run = [
    { task = "generate" },
    { task = "modules" },
    { task = "build" },
    { task = "check" },
]

[tasks.generate]
run = "ogen --target ./api/server/publicapi --package publicapi --config ./api/server/.ogen.yml --clean ./api/server/publicapi.yml"

[tasks.modules]
run = "go mod tidy"

[tasks.build]
run = "go build -trimpath -v --gcflags 'all=-N -l' -o ./bin/cadence ./cmd/cadence"

[tasks.check]
depends = [ "lint", "test:unit" ]

[tasks.lint]
run = "golangci-lint run"

[tasks."test:unit"]
run = "go test ./..."

[tasks."test:e2e"]
run = "go test -tags e2e ./test/e2e/..."
