openapi: 3.0.0

info:
  title: Cadence public API
  version: 1.0.0

tags:
  - name: Bands
  - name: Songs
  - name: Setlists

security:
  - cookieAuth: [ ]

paths:
  /api/band/list:
    get:
      operationId: ListBands
      tags: [ Bands ]
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Band'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: cadencesession
      description: Session cookie for authentication

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponseBody'

  schemas:
    BadRequestResponseBody:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
          example: Invalid data
        data:
          $ref: '#/components/schemas/ErrorData'
      required:
        - code
        - message

    ErrorCode:
      type: string
      enum:
        - invalid_input
        - not_found
        - permission_denied
        - operation_rejected

    ErrorData:
      type: object
      additionalProperties: true
      description: additional information about the error

    Band:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name
